### PR TITLE
feat: add Dragon Warrior channel

### PR DESCRIPTION
**Pull request by campaul**
### Description

Adds a Dragon Warrior channel. The player walks right forever on a looping background. Donations trigger "battles" where a message including the donation amount appears, then the battle UI closes after 1.5 seconds. The donation amount controls which slime appears:

- $0-$99.99 - blue slime
- $100 - $999.99 - red slime
- $1000+ - metal slime

Donations that come in during a battle don't trigger a new battle.

https://github.com/GamesDoneQuick/gdq-break-channels/assets/552768/a33355f7-89aa-4cf1-a0bd-0e64653a40d3

### Checklist:

- [X] I have read and followed the requirements in the [**Contributing** document](https://github.com/GamesDoneQuick/gdq-break-channels/blob/main/CONTRIBUTING.md).
- [X] My code has been tested.
- [X] My commit title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) formatting.
- [X] All the code is my own, or is code I have the rights to, and is being made available under the [Apache License Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).
- [X] My channel contains no first-party Nintendo assets.
- [X] I understand that GamesDoneQuick may reject, make changes to, or choose not to show this channel on broadcast, and that discussion or merging does not guarantee the work will be used.

### CODE REVIEW

**Comment by chrishanel** [comment]
Thank you for the submission!

I think this is a really clever idea, however I feel like there's a lot more potential for taking the concept further. Would it be worth exploring building a true combat cycle into the loop? I could see it be where slimes are randomly spawned with a set HP, and then donations function as attacks worth that much damage.

**Comment by campaul** [comment]
I think that's a great idea, and it shouldn't be too hard to add in based on how stuff is set up. I'll get to work on that.

**Comment by campaul** [comment]
Updates from adding combat:

When a donation comes in, it will trigger a fight. At this point, donations will begin being queued for playback. Donations are applied from the queue until the monster has died. If the queue remains empty for 15 seconds, the monster will run away so we're not stuck on a static combat screen. Events that are in the queue when combat ends are discarded.

The monsters spawn with 2x the initiating donation amount as their HP. This seems like a good difficulty starting point to get a monster that needs more than one hit to kill but doesn't always end up running away. This parameter can be tuned with the `HP_SCALE_FACTOR` const.

"Attacks" now print the charity being donated to. This can be changed with the `CHARITY` const. Not sure if there's a better way to get the charity name so we don't risk this printing MSF during other events.

The state machine has gotten a little more complex than I'd like but it appears to work reliably. I intend to refine this after GDQ is over when I can take more time and focus more, but I don't think I can do much better if this is something we want to merge before the marathon is over.

dw_encounter
dw_attack
dw_victory
dw_run

**Comment by Suyooo** [comment]
> Not sure if there's a better way to get the charity name so we don't risk this printing MSF during other events.

You can get it from the [`currentEvent` replicant](https://github.com/GamesDoneQuick/gdq-break-channels/blob/039987b082713cb453a214746fa2b2023a13021b/src/types/tracker.d.ts#L1-L10)! (The Oregon Trail and Papers Please channels use it, if you want to see more examples)
```tsx
const [event] = usePreloadedReplicant<Event>('currentEvent');
event.beneficiaryShort; // "MSF"
```

**Comment by campaul** [comment]
I made one further behavior change beyond what I described above. Now there is a MAX_HITS number after which the fight will be won regardless of the slime's HP. This is to prevent a single large donation during a steady stream of smaller donations from resulting in a never ending fight.

**Review by chrishanel — APPROVED** [review]
Okay, yeah, these changes are a big improvement. My mind is racing with how much more could be done with this because there's a ton of potential, but I think I'm good with accepting this as is from a design standpoint. Will definitely want Dillon to give it a proper code review, and I can definitely see us wanting to build on the concept more, but well done!

**Comment by campaul** [comment]
I totally agree there's more that can be done with this. I've got several potential ideas I'd like to implement over the coming weeks and I'd love to hear ideas for other things to add to the list. I'll avoid working on these for the moment so there isn't too much churn in this PR, but here's what I'm planning so far: 

- Add in other monsters from the game
- Make it so the monsters have turns (not sure what they should do on their turn, possibly a good place for memes)
- Make all the text easy to configure and extend
- Make the text scroll like it does in the game
- Make the monster fade in and flicker when hit like in the game (I don't think that crosses the line into flashing effect but will skip that if anyone disagrees)
- Add in the player stats box (not sure what should go in there)
- General code improvements (remove magic numbers, more easily extended state machine, etc.)

**Review by VodBox — APPROVED** [review]
Things look good to me to merge the current version. There currently isn't a credit on this channel though, and want to give you a chance to confirm that's correct or to add a credit before I do so.

**Comment by campaul** [comment]
Thanks for checking, that was intentional. I'm having some anxiety about having my name up in front of so many people so I opted to leave it out.

**Pull request merged**
