### PR TITLE
feat: Adding channel with a  V A P O R W A V E   scenery

### PR DESCRIPTION
**Pull request by SushiElemental**
### Description
Adds a new break channel with a 【 V A P O R W A V E 】 scenery.
The channel shows a vaporwave inspired scenery with a magenta sky and blinking stars, a scrolling cyan grid at the bottom and a sun in the center. Donations show up in the upper half of the screen with a hover animation. They will cause a "cloud" in the scenery background to fly up. Subscriptions will show up as hearts flying out from the center.  
The channel number is 15

https://github.com/GamesDoneQuick/gdq-break-channels/assets/46686799/8cea01db-c53b-4d0d-8b92-744d6a83b147

No new libraries are required.

### Checklist:
- [x] I have read and followed the requirements in the [**Contributing** document](https://github.com/GamesDoneQuick/gdq-break-channels/blob/main/CONTRIBUTING.md).
- [x] My code has been tested.
- [x] My commit title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) formatting.
- [x] All the code is my own, or is code I have the rights to, and is being made available under the [Apache License Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).
- [x] My channel contains no first-party Nintendo assets.
- [x] I understand that GamesDoneQuick may reject, make changes to, or choose not to show this channel on broadcast, and that discussion or merging does not guarantee the work will be used.

### CODE REVIEW

**Comment by VodBox** [comment]
Thanks very much for the submission! A vaporwave inspired channel is certainly playing to our designer's interests, and I'm personally keen to have something like this make it in.

That said, I have some feedback, and at least a few barriers to us merging this is that I'd like to see addressed before I can sign off on this.

1. There is at the moment far too much motion.
    1. The pulsing is attention grabbing or distracting in a way that is undesirable. While it's true that we want channels to grab attention, constant rhythmic motion grabs attention even when there's no updates to totals, and makes it hard for a viewer to focus on anything else within the break screen.
    2. When a donation comes in, with both text coming in and the box in the sky appearing and animating out, motion is occurring in three different directions: ground moving left, donation moving outward from center, square moving up from horizon line. Having things going in different directions not only makes it more difficult for someone to latch onto one particular thing, it also means they might not latch onto the donation itself until it's nearly off-screen. That can be disorientating or potentially frustrating.
    3. Even if motion were too be kept, it is either happening too often or too quickly. I personally even get a bit dizzy/nauseous if I look at it for too long myself. Having everything generally be slower when there isn't anything happening would be a big improvement.
2. There are various legibility issues.
    1. The split text colors, while aesthetically cool, makes it hard to read the donation total itself, which is the most important part of the break channels. Especially made difficult because the perceptual brightness difference between the two halves is so large.
    2. The random diacritics added to the event name and the beneficiary make reading those elements more difficult. Especially in regards to the beneficiary name, there it is absolutely crucial that we are representing it plainly.
    3. Having the beneficiary with a small font size and so spread out also makes it less likely to survive downsampling or compression when being broadcast. Generally I would increase the size of this and the event name, should they be kept.
    4. Some of the font color choices being the same as the sky or floor make them difficult to read in front, even with the shadow in place.
3. Generally, we do not allow unvetted names to appear on any broadcast graphics, and so we would not accept showing names on-screen for subscriptions.
4. Event name is redundant, since the event name already shows with the timer element at the top of our break screen, though I acknowledge that removing the event name entirely might result in the channel feeling off-balance should the beneficiary remain.

I want to thank you again for the submission, and I really hope for something that this can reach a place we feel comfortable accepting.

**Comment by SushiElemental** [comment]
Thank you for your feedback! I updated my main branch with the suggested changes and updated how donations are displayed.

- The event title and beneficiary are removed, you're right you would read them once and after that they distract from the rest of the visuals
- Scroll speed of he grid and star twinkling is slowed down
- Subscriptions will now simply spawn a heart outwards from the center
- Donations are now shown similar to the Oregon-Trail channel with a little hover animation and fade-in and fade-out

It's close to bed time over here, need to rebase then tomorrow I guess. Could also update the preview video then as well.

Looking forward to your feedback

**Comment by SushiElemental** [comment]
I think I got that rebasing PRs wrong - should I create another PR or can I still make this work somehow?

Here is the updated preview:


https://github.com/GamesDoneQuick/gdq-break-channels/assets/46686799/8cea01db-c53b-4d0d-8b92-744d6a83b147

**Comment by SushiElemental** [comment]
Hi! Okay I fixed my screwup in the Git history.

Please take a look again.

**Pull request merged**
