### PR TITLE
Add Final Fantasy Shop channel

### PR DESCRIPTION
**Pull request by dylbyl**
### Description
Adds a channel that mimics Final Fantasy 7's shops. Donations cause the menu to "scroll" down and reveal new Square Enix themed items with unique descriptions and icons. The item's price is the amount donated, and larger donations result in "better" items. A different "theme" is used each time the channel loads to make it evoke different games: FF7, FF8, Chrono Trigger, Dragon Quest, FF4. New themes and items can easily be added or removed.

normal-use

ff8
chrono-trigger
dq3
ff4

### Checklist:
- [x] I have read and followed the requirements in the [**Contributing** document](https://github.com/GamesDoneQuick/gdq-break-channels/blob/main/CONTRIBUTING.md).
- [x] My code has been tested.
- [x] My commit title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) formatting.
- [x] All the code is my own, or is code I have the rights to, and is being made available under the [Apache License Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).
- [x] My channel contains no first-party Nintendo assets.
- [x] I understand that GamesDoneQuick may reject, make changes to, or choose not to show this channel on broadcast, and that discussion or merging does not guarantee the work will be used.

### CODE REVIEW

**Comment by dylbyl** [comment]
I've added a fake scrollbar to better visualize the scrolling action. This resets its position each time the channel loads, or if the bar reaches the bottom.
scroll

**Review by chrishanel — DISMISSED** [review]
I think this is a concept you've implemented pretty well, and I love the opportunities for us to add more items that include inside jokes or memes that happen organically during the event. I also appreciate the extra theming you've offered as well.

I'm going to approve the design and implementation. If Dillon approves on the tech side, then we'll be good to go.

Thanks very much for the submission!

**Comment by dylbyl** [comment]
@chrishanel The scrollbar messed up the alignment of the cursor and the bottom item, so I snuck in another commit for that. It says above that I dismissed your review, so I'm sorry if you need to re-approve. I'll be more aware of that next time!

**Comment by chrishanel** [comment]
first of all how dare you

**Review by VodBox — DISMISSED** [review]

**Review by VodBox — APPROVED** [review]

**Review by chrishanel — APPROVED** [review]

**Pull request merged**
