### PR TITLE
feat: add Shovel Knight channel

### PR DESCRIPTION
**Pull request by meseck**
### Description
A Shovel Knight channel, where the knight himself shovels the donation in the form of treasure from the ground.

It's not one hundred percent perfect yet. I saw that the Celeste channel was rejected, and before I invest any more time in this fun little project, I wanted to make sure it was even considered as a channel.

CleanShot 2023-06-01 at 22 31 03

### Checklist:

- [x] I have read and followed the requirements in the [**Contributing** document](https://github.com/GamesDoneQuick/gdq-break-channels/blob/main/CONTRIBUTING.md).
- [ ] My code has been tested.
- [x] My commit title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) formatting.
- [x] All the code is my own, or is code I have the rights to, and is being made available under the [Apache License Version 2.0](https://www.apache.org/licenses/LICENSE-2.0).

### CODE REVIEW

**Comment by chrishanel** [comment]
Hey! Thanks so much for the submission!

You're right in that this is sadly too recent a game to feel comfortable using as a break screen channel, and I'm going to have to say no. However this looks really pretty and I would love to see any other ideas you might want to contribute. 

Apologies, and thanks again.

**Comment by meseck** [comment]
Hey, glad you liked it, thanks for the kind words.

It would be nice to have more 'clues' in the CONTRIBUTE docs about what works and doesn't work. The first 'Shovel Knight' is almost 10 years old and even 1 year older than Undertale, so I was actually hoping it would fit.

It was still really fun to work on and if I have another idea I will surely give it another try. 

Keep up the good work with the overlays, I'm a fan!

**Comment by chrishanel** [comment]
Totally understand why that could feel a bit disorienting. In the case of Undertale, the dev has given explicit permission to remix assets and make fanworks, so we felt comfortable allowing it.

The other factor is that while the original Shovel Knight game is older, the franchise is still active and publishing new content with the same aesthetic, thus we would consider it too contemporary. 

I'll take a look at the contributing document again and see if we can't offer more guidance.

**Comment by meseck** [comment]
Thank you for taking the time to explain it to me in further detail! I can understand the problem.

**Pull request closed without merging**
